[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = ["pre-commit"]
